### PR TITLE
Add sale price support

### LINKED ISSUE #129: Add sale price support
Recently added sale prices are currently not supported in this design. Sale prices should be displayed in auto-generated product layout.

### PR DESCRIPTION
**Pull request by PeeterPaal**
Adds sale price support, which includes:
- displaying sale prices on auto-generated product pages
- making sale prices react to design editor colours on buy buttons & auto-generated product pages

Closes #129 

Testing:
Make sure that sale prices are displayed on auto-generated product pages and prices on buy buttons react to changes in design editor.

### CODE REVIEW

**Comment by t-p-developer** [comment]
Why does the product list not show the sale price, only the line-through initial price?

**Comment by PeeterPaal** [comment]
>Why does the product list not show the sale price, only the line-through initial price?

I did not notice the dark background styles at first, as these are pre-defined and not configurable via design editor. Should be fixed now.

**Review by piiamatsi — APPROVED** [review]
Looks good!

**Review by tanelj — APPROVED** [review]
Nice!

**Pull request merged**
