### PR TITLE
Add product & product list layouts 

### LINKED ISSUE #96: Add “Product” and “Product list” layouts.
PR #97 
Add
* [ ] Product list layout
* [ ] Product layout

### PR DESCRIPTION
**Pull request by siimha**
Close #96 
## Some guides for testing:
- [x]  Check if bgpicker, image drop area and page/article image saving works properly in the following layouts:
  - [x]  **Product list**
  - [x]  **Product**
- [x] Check if **Product list** layout works properly everywhere.
- [x] Check if **Product** layout works properly everywhere.
- [x] Check if **Blog & news** layout didn't broke down.
- [x] Check if **Product list** layout works up to second level in menu.
- [x] Check if **Product list** works for _root item_ (first page).
- [x] Check if **Product** works for _root item_ **(first page)**.
- [x] Check if main menu in desktop didn't broke down.
- [x] Check if main menu in mobile didn't broke down.
- [x] Do a small check for all other layouts to see if something got broken.
- [x] If **first page** is used as **Product list**, there's an option to hide _product_ related pages from main menu. Check if that works as intended.

### CODE REVIEW

**Comment by siimha** [comment]
* [ ] If parent page of the "Product" or "Product list" pages is hidden, the children are not listed as products/categories & not displayed. Also breadcumbs are missing & you cant add subpages to visible children if parent page of the "Product" or "Product list" pages is hidden.

**Comment by SSirjes** [comment]
* [ ] product related layout are not displayed under main menu

**Comment by SSirjes** [comment]
* [ ] mobile menu doesn't open (http://recordit.co/Cfi25DzyPe)

**Comment by siimha** [comment]
On page loading all possible breadcrumbs are rendered for all product list:
* [ ] Render only selected item breadcrumbs

Fix for menu-breadcrumbs-items-loop:
`{% for i in (1..5) %}
  {% assign level_str = 'menuitems_with_hidden_on_level_' | append: i %}
    {% for item in site[level_str] %}
      {% if item.selected? %}
      <span class="menu-separator">/</span>
      {% menulink item wrapper-tag="li" wrapper-class="menu-item" %}
     {% endif %}
   {% endfor %}
{% endfor %}`

**Comment by SSirjes** [comment]
* [x] ` .menu li.active a` style is missing

_Active menu item should look like this:_
screen shot 2018-04-26 at 16 38 37

**Comment by SSirjes** [comment]
* [ ] If content background is dark, then breadcrumbs menu item color should get from design editor Content >Sub menu > Normal color

**Comment by SSirjes** [comment]
* [ ] bind breadcrumbs menu separator color with design editor Sub menu > Normal color

**Comment by SSirjes** [comment]
* [ ] fix product related layouts names.

screen_shot_2018-05-24_at_09_36_43

Product list layout name should be 'product_list'.
Product layout name should be 'product'.

**Pull request merged**
